### ISSUE TITLE
ContextMenu closes when hovering a validation error

### ISSUE THREAD

**Issue by brownieboy** [josdejong/svelte-jsoneditor#110]
So this is on the JSON Schema Validation example, after running `yarn dev` in the repo.

I'm trying to edit the `age` value via the context menu.   My natural motion then is to move the mouse to the right and down simultaneously,in order to get to the **Edit value** button.   But doing so leaves the menu trigger area completely, so causing the menu to disappear.

![svelte-delay-needed](https://user-images.githubusercontent.com/1781909/176617275-c5724610-291d-4d33-af0f-2cef8fcbff9d.gif)

To actually reach the **Edit value** button, I have to move the move first down, and _then_ to the right, as shown at the end of the animated GIF above.  That's not really intuitive though.

So maybe some kind of delay here before the context menu closes on exit?   A half or second or so ought to be enough.

**Comment by josdejong** [comment]
Thanks for reporting, the screenshare is very helpful. 

This is a bug I noticed before but haven't addressed yet. The issue is that the context menu closes when you hover over a validation warning (which also opens a popup). I'll adjust the title of this issue accordingly.

You will not encounter the issue when you right-click to open the context menu, since the mouse will already be on top of the context menu in that case.
