### ISSUE TITLE
Validator causes cursor position to be lost when onChange fires

### ISSUE THREAD

**Issue by djbutler** [josdejong/svelte-jsoneditor#118]
When I include an `ajv` validator, the cursor position is lost whenever the contents of the editor change.

**Comment by djbutler** [comment]
Here's an example: https://codesandbox.io/s/svelte-jsoneditor-react-forked-9sp6lu .

Expected behavior: can edit without losing cursor position.
Actual behavior: cursor position is lost after edits.

**Comment by josdejong** [comment]
Thanks for reporting. I had a look, and it turns out that the cursor position is being reset only when you replace the validator. That was caused by a workaround to enforce the editor to trigger validation again after you change the validator. In you're code, with every re-render, you're creating a new validator and send that to the editor. So that triggers resetting the cursor position with every re-render.

I've created a fix for it.
