### ISSUE TITLE
When readOnly is set true,I can not select all by "command + A" in text mode 

### ISSUE THREAD

**Issue by masquerader0** [josdejong/svelte-jsoneditor#142]
It works in v0.7.3 ,but not in 0.7.4[https://codesandbox.io/s/svelte-jsoneditor-react-forked-bnhg9q](url)

**Comment by josdejong** [comment]
Thanks for reporting. 

Hmmm, this is interesting. In v0.7.4, we disabled the editor when readOnly to prevent the editor from opening the keyboard when on a mobile device, see #130. 

It is useful though to still be able to select and move through the editor. I'm not sure how we can solve both issues. Any suggestions @masquerader0 or @fonov?

**Comment by bhl-0** [comment]
I'm guessing the reason we want to do command + A in readOnly mode is to select & copy all to clipboard.
Cant we just add a "copy all text" button in menubar in readOnly mode?

**Comment by josdejong** [comment]
I like that idea, thanks. 

The `tree` mode also has a copy button when readOnly, though that will copy the selection and not the full document. I think it's not a big problem if that is not consistent. I expect though that `tree` mode will still open the mobile keyboard right now, and if so, we should look into that (see also #130).

**Comment by josdejong** [comment]
Fixed via https://github.com/josdejong/svelte-jsoneditor/commit/99922dc3f5f981a742bb2a2b31151bfe1c09ecb3, but this fix may bring back the issue that #130 fixed: the mobile keyboard opens when in readOnly mode. It may be fixed in a different way already by fixing #231 via https://github.com/josdejong/svelte-jsoneditor/commit/5df57eea7a8c6600efb4f8f1a41ad338fce77e0a, I'll have to validate that.
