### ISSUE TITLE
not working in svelte REPL, any hints?

### ISSUE THREAD

**Issue by zahachtah** [josdejong/svelte-jsoneditor#15]
I get: " Could not load https://unpkg.com/tty@1.0.1/index.js (imported by https://unpkg.com/debug@4.3.2/src/node.js): Cannot find "/index.js" in tty@1.0.1" when copy pasting  the basic svelte example from the example folder into a svelte REPL.

**Comment by josdejong** [comment]
Yeah, the REPL doesn't work unfortunately. The reason is that the code is written with SASS and one dependency of the editor loads a JSON file. So that requires a Svelte setup which pre-processes SASS and JSON. See setup: https://github.com/josdejong/svelte-jsoneditor#svelte-setup

I'm not happy with this setup (forcing consumers to set up these pre-processors), but as far as I understand it it's currently the recommended way in Svelte, [see docs Consuming components](https://github.com/sveltejs/component-template#consuming-components). If there is a better way I would love to hear!!

**Comment by zahachtah** [comment]
ok, thanks. Not much to do then :-)
