### ISSUE TITLE
Using vanilla-jsoneditor gets: ERR_REQUIRE_ESM

### ISSUE THREAD

**Issue by kirbdee** [josdejong/svelte-jsoneditor#201]
When importing vanilla-jsoneditor, and compiling with TS/Webpack down to commonjs we're getting run time error of ERR_REQUIRE_ESM. Wondering if we could have a build simply be commonjs to have more compatibility overall

**Comment by josdejong** [comment]
Thanks for reporting Kirbs. The library indeed only publishes ESM right now. Let's keep the discussion focused and continue in #196. Can you explain your case there and explain why you can't use ESM? (if you can't use ESM in your project you'll probably hit these kind of issues more and more since the industry is moving to ESM).
