### ISSUE TITLE
 long string overflowed the vertical gray line when wrap 

### ISSUE THREAD

**Issue by XueMeijing** [josdejong/svelte-jsoneditor#228]
Hi,
Thanks for ur work.However, it seemes there are still two issue exist in 0.14.9.
First,  in text mode, long string overflowed the vertical gray line when wrap. The long string is in one node In successor, but it divide into muti nodes in classic.

![image](https://user-images.githubusercontent.com/35559153/220809750-2d79cc88-ee6a-4e4a-b7c0-9a40806fdd15.png)

The other is about plain obj and array  when format. It works normal when parser is default. But when i changed it into LosslessJSONParser, plain obj and array expand again like https://github.com/josdejong/svelte-jsoneditor/issues/220
What shuold i do to solve this ?

**Comment by josdejong** [comment]
About the LosslessJSONParser: can it be that you're not using the latest version `2.0.6`? The formatting issue was fixed in that version.

That text wrapping doesn't look very neat, with the indentation lines overlapping it. I guess we'll have to see if it is possible to customize CodeMirror to apply indentation to the wrapped lines, like discussed here: https://discuss.codemirror.net/t/making-codemirror-6-respect-indent-for-wrapped-lines/2881/3

Help would be welcome.

**Comment by XueMeijing** [comment]
yeah! When i upgraded LosslessJSONParser to 2.0.6 it works great!

I have debuged about text wrapping, but i haven't find a workaround yet, i'll try latter
