### ISSUE TITLE
Support for theming

### ISSUE THREAD

**Issue by bostondevin** [josdejong/svelte-jsoneditor#29]
How can I theme up this puppy? Any clues?

Thanks!!! Great work!

**Comment by josdejong** [comment]
> How can I theme up this puppy?

trying to tame this puppy? 😉 

Theming is not yet supported. I want to look into using CSS variables for this. Shouldn't be too hard to turn the current SASS variables into CSS variables. Though it may require some rework to nicely support a dark theme: need to introduce a variable text color for that instead of using "black" everywhere throughout the code.

There is one catch: for the code editor (Ace editor), the styling must be done via a special AMD module containing the styling as a CSS string, see [theme-jsoneditor.js](https://github.com/josdejong/svelte-jsoneditor/blob/main/src/lib/components/modes/codemode/ace/theme-jsoneditor.js). 

Help would be very welcome!

**Comment by Kutikov** [comment]
> > How can I theme up this puppy?
> 
> trying to tame this puppy? 😉
> 
> Theming is not yet supported. I want to look into using CSS variables for this. Shouldn't be too hard to turn the current SASS variables into CSS variables. Though it may require some rework to nicely support a dark theme: need to introduce a variable text color for that instead of using "black" everywhere throughout the code.
> 
> There is one catch: for the code editor (Ace editor), the styling must be done via a special AMD module containing the styling as a CSS string, see [theme-jsoneditor.js](https://github.com/josdejong/svelte-jsoneditor/blob/main/src/lib/components/modes/codemode/ace/theme-jsoneditor.js).
> 
> Help would be very welcome!

Sorry, theme-jsoneditor is not available anymore. Can you update link?

**Comment by josdejong** [comment]
Ah, two things:

1. Ace editor has been replaced with Code Mirror, which doesn't need this separate theme-jsoneditor.js anymore
2. A few days ago I started working on normalizing the CSS classes with a `jse-` prefix, and introduce CSS custom variables. So easy custom styling will be available soon (within weeks). See this branch (very much a WIP right now): https://github.com/josdejong/svelte-jsoneditor/tree/feat/css_refactoring

See also #57

**Comment by josdejong** [comment]
I've just published `svelte-jsoneditor@0.3.49` which can be styled using css variables. A dark theme is included.

Docs: https://github.com/josdejong/svelte-jsoneditor#styling
Examples: two related examples can be found in the [examples section](https://github.com/josdejong/svelte-jsoneditor/tree/main/src/routes/examples)

Toggling light/dark mode can be tried out in https://jsoneditoronline.org (v6.1.0).
