### ISSUE TITLE
Use MDI icons

### ISSUE THREAD

**Issue by SamMousa** [josdejong/svelte-jsoneditor#325]
Hey, very nice that you've rebuild this using Svelte! (Even though that was a while a go, I did not notice it until just now).

I'm a big fan of the icon library at https://pictogrammers.com/library/mdi/. Not just the icons themselves, but the open source & community approach to development are very nice.

Would you consider switching to that library for icons? I've built a fully tree-shakeable library for Svelte that allows you to easily use these icons from your Svelte library:  https://github.com/collecthor/svelte-material-icons

I could work on a PR if you are open to it!

**Comment by josdejong** [comment]
Thanks for your suggestion Sam. I hadn't seen Pictogrammers before. It looks really neat and complete. I've bookmarked it :)

There are a number of alternatives to FontAwesome, however, the icons we use from FontAwesome work fine and are open source. At this point I prefer staying with FontAwesome since it is most mainstream and proven to be stable.
