### ISSUE TITLE
Question: How to allow only certain fields of Json being editable ?

### ISSUE THREAD

**Issue by himalaya0035lumiq** [josdejong/svelte-jsoneditor#348]
Using **vanilla-jsoneditor": "^0.19.0",** for react
Let's take this json for example
`{
    "name" : "sample",
    "age" : "22",
    "address" : {
        "city" : "sample city",
        "country" : "sample country"
    }
}`

For a certain reason, I only want age and "address.country" to be editable and not other fields when I double click on it.
is there a way to achieve the same ?

Thanks

**Comment by josdejong** [comment]
There is currently no good way to do something like that. You can make specific fields read-only or customize how they are rendered using `onRenderValue`. But you can't really control it, since the user can work around it by renaming the key, then editing, and then renaming it again, or pasting content using Ctrl+V, or tricks like that.

It would be nice to have better control over this though, we could work out a plan for that. 

Related: #342

**Comment by himalaya0035lumiq** [comment]
and please tell me how to get rid of context Menu.
Thanks
