### ISSUE TITLE
When using the CDN version an error occurs

### ISSUE THREAD

**Issue by chrisschippers** [josdejong/svelte-jsoneditor#355]
When using the CDN version the following error occurs (in the console)

Uncaught TypeError: Failed to resolve module specifier "immutable-json-patch". Relative references must start with either "/", "./", or "../".

import { JSONEditor } from 'https://cdn.jsdelivr.net/npm/vanilla-jsoneditor/index.js'

This is using the sample in the repository.

Also using the sample at:
https://jsbin.com/gatibux/edit?html,output

Last week it worked fine.

**Comment by josdejong** [comment]
Since the last version, `v0.2.0`, you have to use the `standalone.js` bundle:

```js
import { JSONEditor } from 'https://cdn.jsdelivr.net/npm/vanilla-jsoneditor/standalone.js'
```

I indeed see that the jsbin example wasn't yet updated, I've fixed that now. Thanks for reporting!

Docs: https://github.com/josdejong/svelte-jsoneditor/blob/main/README-VANILLA.md#use
Changelog: https://github.com/josdejong/svelte-jsoneditor/blob/main/CHANGELOG.md#0200-2023-12-06
