### ISSUE TITLE
classic tree view is necessary

### ISSUE THREAD

**Issue by wongshung** [josdejong/svelte-jsoneditor#61]
Would sugguest to keep tree view option. Some guys might like to use new view. But some guys might still get used to classic tree view mode. So better keep it there.

**Comment by josdejong** [comment]
Hi @wongshung , thanks for your input. 

The tree view is still available, you can toggle between tree/code mode:
![afbeelding](https://user-images.githubusercontent.com/568626/162899945-50b67253-b379-46e5-9562-67a48b65fcfd.png)

Is that what you mean? Or did you like the classic tree view better than the new treeview?

**Comment by wongshung** [comment]
I like the classic tree view better than new treeview. If a lot of ppl prefer the classic tree view, maybe you should consider keep the classic tree view. If very few ppl like that, then i think it is ok to just maintain the new view.

**Comment by josdejong** [comment]
Ah ok, I understand you. 

Can you explain what you like better about the classic tree view?

**Comment by wongshung** [comment]
I just think that classic tree view is much simple and clear. New tree view is a bit complicated. E.g, showing {2} is better than { 2 props } and [1] is better than [ 1 items ], as {} and [] are enough to know that they are props or items, but much simple and clear.

**Comment by josdejong** [comment]
I get what you mean, thanks for your explanation. 

You're right, the new view has a bit more "noise" in that regard. It tries to stay a bit closer to the original JSON by always showing the brackets both when the array or object is collapsed or expanded. Also, the tag `x items` stays visible for arrays when expanded since this information is quite relevant to have a feel of what amount of data you're dealing with.

I've tried out your idea of just showing the number `7` instead of `7 props` or `7 items`. I'm afraid that this gives _too little_ context and people may wonder what this floating number means. It's a challenge trying to strike a good balance between a clean, minimal UI on the one side, and giving enough context, and information for people to understand what they see on the other side. I feel it's still best to keep the suffixes `... items` and `... props`, but I'm always open to reconsider any new insights or ideas.

Note that you can keep using the classic version if it works better for you: https://jsoneditoronline.org/classic/index.html

**Comment by yellowjacketcoder** [comment]
+1 I would also like to vote in the favour of the classic tree view because of the reason @wongshung mentioned already and also because the classic view formatted the code automatically when switching to tree mode and then back to code mode(which I believe can also be achieved with the new layout but more so that we have gotten used to the classic view. What exactly do I like about the old version better? I can't put it into words cause I am not a design expert but it's subjectively better for a lot of us

**Comment by josdejong** [comment]
Thanks for your feedback Pranjal 👍 

> and also because the classic view formatted the code automatically when switching to tree mode and then back to code mode

🤔 hm yeah. I will give that some more thought and see if it makes sense to re-implement that again. On the other hand, instead of going to tree mode and then back to code mode, you could also just click the "Format" button once or press `Ctrl+I`?

> What exactly do I like about the old version better? I can't put it into words cause I am not a design expert but it's subjectively better for a lot of us

Yes that makes sense, it can be just personal preference and not a specific reason.

**Comment by tsptylertech** [comment]
Also, in the new treeview, it's not very intuitive... for instance, I need to convert something like this:
  "junk": {
    "0": {
      "status": "Draft",
      "timestamp": "2022-04-14T03:37:56.397Z",
      "userId": "abcdef"
    },
    "1": {
      "status": "Submitted",
      "timestamp": "2022-04-14T03:39:11.283Z",
      "userId": "abcdef"
    }
}

to 

  "junk": [
     {
      "status": "Draft",
      "timestamp": "2022-04-14T03:37:56.397Z",
      "userId": "abcdef"
    },
    {
      "status": "Submitted",
      "timestamp": "2022-04-14T03:39:11.283Z",
      "userId": "abcdef"
    }
}

In the old treeview, you would just right click the left arrow on Junk, click Type, and click Array... and it would convert it... 
In the new treeview, I could not even figure out where to do that...

**Comment by josdejong** [comment]
Thanks for your input @tsptylertech. Can you explain if you need this a lot, and how it comes that you get data like this? I mean where is it coming from? 

I did build this feature 11 years ago in the classic editor but never needed it myself. If it turns out to be a common case I can see if we can add provisioning for it in the context menu. In the new editor there is no ready made feature for this case, but you can turn your object into an array using Transform with the following JavaScript query:

```js
function query (data) {
  return Object.values(data)
}
```

Transform allows you to transform your JSON in any way you want, it is very flexible and powerful.

**Comment by tsptylertech** [comment]
Another dev turned me onto your online tool.
Now, all the devs, that I've turn on to your tool, use this feature.  We get JSON out of datadog, and several other tools, that we use in our debugging.

We paste the JSON in and use this tool to transform all the original arrays (which our tools convert to what you see in my former post) back to arrays.  That way we can use the JSON in our debugging of issues.

With the new tree view, we would have to paste our JSON, code out the function to convert the "adjusted" arrays.  Then, for every new JSON we would have to cut and paste coding it out JSON array that was broken, that we paste in there.

The classic tree view is great... we just paste in the JSON, and then we can convert back and forth between object types to get our JSON into the original form we need it in, so we can use it for debugging our code...

**Comment by josdejong** [comment]
Ah, OK. So it is query output from a logging tool like DataDog. It feels a bit odd to get back an object instead of an array for your data when querying logs. Is it some limitation in the query options of DataDog that it is not possible there, or is it something specific to the data of your company?

**Comment by tsptylertech** [comment]
It's a "feature" of datadog when you hand it JSON as part of the data it "logged"; datadog converts the arrays into objects within their viewer...

We have found this to be true with a couple of other tools we use, when you give it JSON that have objects which are arrays, those tools convert the arrays from "abcd": [ { "a": "b", "c": "d"}] to "abcd": {"0": { "a": "b", "c": "d"}}, etc, etc...

I just cannot remember the other tools off the top of my head this morning.

**Comment by josdejong** [comment]
If it's a generic thing for tools like Datadog and others, it makes definitely sense to support converting from object to array. I'll change the current "replace with array/object" (making a new empty array/object) with "convert to array/object", so we basically have the behavior of the classic tree editor back.

**Comment by tsptylertech** [comment]
Great, that will work for us...

**Comment by josdejong** [comment]
@tsptylertech the conversion functionality is available now in `svelte-jsoneditor@0.3.43`, web application `v6.0.5`. 

Just right click on the open/close bracket of an array/object and then click the convert button from the context menu.

**Comment by josdejong** [comment]
👍 good to hear 😄 . If you have more ideas/suggestions please let me know.

**Comment by bgsquared** [comment]
Why did you get rid of left controls for moving and menu?  Am I missing something? That was more intuitive/ simpler to see than having to get the highlight correct in order to move, insert, duplicate, remove etc.  Please bring back this view:
![Capture](https://user-images.githubusercontent.com/36642420/164547915-daeff620-f075-4981-bbdc-4975cb1842f1.JPG)

**Comment by josdejong** [comment]
Thanks for your feedback @bgsquared. You're not the only missing these buttons, multiple people are confused about it. 

The idea is as follows:

- in the classic editor you can left-click the context menu button on the far left side of the item that you want to operate on
- in the new editor you can right-click on top of the item (or selected items) that you want to operate on

The new editor allows for more streamlined editing: your eyes and mouse can stay on top of the data that you're operating on. You can select a part of the data by dragging with the mouse. You can just grab the selected data itself and drag it up and down, or right-click the selection or any key or value to open up the context menu. It's all right under your "finger tips". You do not have to _first_ select an item and _then_ right-click it, you can directly right-click any item to get it selected and open the context menu, the number of clicks needed to perform an action are the same, and typically you need less mouse movement now to get a series of changes done.

This concept is not something new: it is the basis of how many editors work, from Notepad to Word and Excel. You select some text/data, and then right-click to open a context menu to operate on it. Does that make sense?

I think part of the confusion is that it wasn't really discoverable that you can use right-click in the new editor. I've improved on that by displaying a tip in the context menu explaining this. Does that help?

**Comment by zehawki** [comment]
>  classic view formatted the code automatically when switching to tree mode

@yellowjacketcoder see thats your specific preference. Someone else may find it confusing that they start with code-compact view > switch to tree > and when back to code it has suddenly become code-format view. A UI should not spring surprises on users.

-----

However the class tree was possibly better in the following way: it had affordances (pull bars and action button) on the left that clearly showed that various nifty things could be done. 

> it is the basis of how many editors work, from Notepad to Word and Excel. You select some text/data, and then right-click to open a context menu to operate on it. Does that make sense?

It works there since 2 generations of users have been trained already to expect it. Whereas it may not be obvious in **this** editor.

Also power users and older people much rather prefer explicit menu elements.

**Comment by zehawki** [comment]
Its exactly as you mention - both methods have value. 

I suggest waiting for some more people to chime in before changing anything. (Design and UI are an endless slippery slope, and it will never satisfy everyone's idiosyncrasies.)

**Comment by josdejong** [comment]
Well said, agree. Thanks for your inputs.

**Comment by josdejong** [comment]
Closing this issue now. Thanks again for the feedback.
