### ISSUE TITLE
rollup error: Cannot read file .svelte-kit/tsconfig.json

### ISSUE THREAD

**Issue by milahu** [josdejong/svelte-jsoneditor#69]
error

```
$ rollup --config rollup.config.bundle.js

src/lib/index.js → package/dist/jsoneditor.js...
(!) Plugin typescript: @rollup/plugin-typescript TS5083: Cannot read file '.svelte-kit/tsconfig.json'.
[!] (plugin typescript) Error: @rollup/plugin-typescript: Couldn't process compiler options
```

this file is missing

https://github.com/josdejong/svelte-jsoneditor/blob/a36312eff5774d962a072a31c2bf7c5eabdb5e1b/tsconfig.json#L2

fixed (?) by removing the line from tsconfig.json

**Comment by milahu** [comment]
pardon my brevity. to reproduce:

```
cd $(mktemp -d)
git clone --depth 1 https://github.com/josdejong/svelte-jsoneditor
cd svelte-jsoneditor
npm install
npm run build
```

maybe you have a private `.svelte-kit/tsconfig.json` file?

**Comment by josdejong** [comment]
Thanks, I can reproduce this issue. 

In a fresh clone of the project, the folder `./.svelte-kit` doesn't exist: that is generated as soon as you run `svelte-kit build` or `svelte-kit dev`. So to fix this, something must trigger to initialize creation of this folder, before running the packaging with rollup. I've added running `svelte-kit sync` now in order to fix it.
